"""message

Revision ID: 1dfd106bf122
Revises: 
Create Date: 2024-03-26 20:59:11.572301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dfd106bf122'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_base_model_created_at'), 'base_model', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_base_model_deleted_at'), 'base_model', ['deleted_at'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_base_model_deleted_at'), table_name='base_model', schema='public')
    op.drop_index(op.f('ix_public_base_model_created_at'), table_name='base_model', schema='public')
    op.drop_table('base_model', schema='public')
    # ### end Alembic commands ###
