// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpXXR-XL59nR7XuNMKkYCNeCIByvh91nI',
    appId: '1:758471968343:web:5addfd29ae5a1ede800512',
    messagingSenderId: '758471968343',
    projectId: 'mobileappfff',
    authDomain: 'mobileappfff.firebaseapp.com',
    storageBucket: 'mobileappfff.appspot.com',
    measurementId: 'G-ZT6JJV8B57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-d9JncvbtJglKLpuVkuhxx3jS8FLB4Lo',
    appId: '1:758471968343:android:1f96ff75809dc5d5800512',
    messagingSenderId: '758471968343',
    projectId: 'mobileappfff',
    storageBucket: 'mobileappfff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA78hPNtl-1tiK43RfTtDdjfrPZiN8cDes',
    appId: '1:758471968343:ios:edaebd5f9524c552800512',
    messagingSenderId: '758471968343',
    projectId: 'mobileappfff',
    storageBucket: 'mobileappfff.appspot.com',
    iosBundleId: 'com.example.appPlanningBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA78hPNtl-1tiK43RfTtDdjfrPZiN8cDes',
    appId: '1:758471968343:ios:edaebd5f9524c552800512',
    messagingSenderId: '758471968343',
    projectId: 'mobileappfff',
    storageBucket: 'mobileappfff.appspot.com',
    iosBundleId: 'com.example.appPlanningBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpXXR-XL59nR7XuNMKkYCNeCIByvh91nI',
    appId: '1:758471968343:web:526386b7adf35548800512',
    messagingSenderId: '758471968343',
    projectId: 'mobileappfff',
    authDomain: 'mobileappfff.firebaseapp.com',
    storageBucket: 'mobileappfff.appspot.com',
    measurementId: 'G-E581HPL8F8',
  );

}